runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img
  application_readable: true

- url: /api/.*
  script: main.app

#libraries:
#- name: svgwrite
#  version: 1.1.9
