runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^node/.*

handlers:
- url: (.*)/
  static_files: app/index.html
  upload: app/index.html

- url: /js
  static_dir: app/js

- url: /css
  static_dir: app/css

- url: /img
  static_dir: app/img

- url: /views
  static_dir: app/views

- url: /api/.*
  script: main.app